### ISSUE TITLE
Document review for version 2.0.0

### ISSUE THREAD

**Issue by guilhemmarchand** [guilhemmarchand/TA-jira-service-desk-simple-addon#101]
Document review for version 2.0.0

- review distributed setup
- migration steps from version 1.x to 2.0

**Comment by zerodago** [comment]
will we have version 2 ?? Excellent!
What news will we see?

**Comment by guilhemmarchand** [comment]
Yes @zerodago ;-) We will:

https://ta-jira-service-desk-simple-addon.readthedocs.io/en/testing/releasenotes.html

Version 2.0.0
=============

- Migration to ucc-gen (Splunk Add-on factory framework), refreshed modern configuration UI
- Support for JIRA multi tenant accounts (Multiple JIRA accounts can now be set up targeting different JIRA instances)
- Support for Personal Access Token (PAT) authentication (See: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html)
- Support for Proxy authentication
- Python 3 only support (Splunk 7.x is not supported any longer)
- Support for attachments in Excel (xlsx) format
- Support for attachments with the issue dedup feature

It is in testing branch already:
https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/tree/testing

Pretty much ready, need a migration page (the account need to be created) plus some final testing
