### ISSUE TITLE
SSL verification failed error with self-signed certificate

### ISSUE THREAD

**Issue by jabatrox** [guilhemmarchand/TA-jira-service-desk-simple-addon#11]
Hi,

We are using a self-signed certificate on Jira Service Desk. We have internally validated it in our firewall and added it to JSD conf, so it appears as valid when we connect through the browser. Besides, when we set up the connection settings in the Splunk add-on, everything seems to work fine, and we are able to get the projects, priorities, etc.

However, when we define an alert action in real time, and it gets triggered, the event always appears as failed due to a SSL_VERIFICATION_FAILED error.

We have checked the settings and the SSL verification checkbox is disabled (although we have tried with it on enabled as well).

Would you have any idea of why this might happen, and how can we fix it? Or would it be possible to specify the path to the certificate, so it will use that one to verify the connection?

Thank you

**Comment by guilhemmarchand** [comment]
Hi @jabatrox 

Sorry for some reasons I didn't get notice of the issue.
Will review shortly.

Kind regards,

Guilhem

**Comment by guilhemmarchand** [comment]
The issue was identified, and will be fixed very shortly.

**Comment by guilhemmarchand** [comment]
@jabatrox 

Addressed by version 1.0.9 published in Splunk Base.
