### ISSUE TITLE
Splunk cloud vetting failed, need to upgrade to python 3

### ISSUE THREAD

**Issue by guohuang** [guilhemmarchand/TA-jira-service-desk-simple-addon#114]
do you have a plan to upgrade this TA? if not I can submit a PR

**Comment by guilhemmarchand** [comment]
Hi @guohuang !

Where's that vetting coming from?
That's pure bullshit (apologize the language)

The latest release is already vetted for Splunk Cloud (which you can see in Splunk Base)
The Addon is only compatible with Python3, which is even explicitly defined in the related conf.

Last, the Addon is based on the Splunk ucc lib which is the up to date reference framework.

So yes the app is already py3 only, and already vetted for Cloud

Guilhem

**Comment by guilhemmarchand** [comment]
Hi @guohuang 

I am going to close this issue, let me know if you need anything more from, as I was saying the latest release app is already vetted for Splunk Cloud.
