### ISSUE TITLE
Add option for adding a comment for existing issues

### ISSUE THREAD

**Issue by maxi-gc** [guilhemmarchand/TA-jira-service-desk-simple-addon#12]
Add an option to create a comment for existing issues (existing based on description and body) instead of generate a new issue. This is very much desirable in many environment to avoid spamming recipients where an issue is being fixed but the detection is daily or ongoing

**Comment by guilhemmarchand** [comment]
@maxi-gc 

The version 1.0.11 of the Add-on for JIRA is live in Splunk Base, and implements a brand new feature to address this feature request.

**The feature is documented within the application and in the on-line docs:**
[https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/userguide.html#jira-dedup-behaviour](https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/userguide.html#jira-dedup-behaviour)

In a few words, this relies on performing md5 calculation over the JIRA issue and achieving comparison with records stored in a dedicated KVstore.
When the option is enabled, the backend will add a comment (which comment content can optionally be controlled) to the original JIRA issue.

Let me know if you have any question.

Guilhem
