### ISSUE TITLE
Error between Splunk and Jira

### ISSUE THREAD

**Issue by rafamss** [guilhemmarchand/TA-jira-service-desk-simple-addon#123]
Hi dear developer,

I'm using your integration, and we started to receive this message, and any alert is being sent to Splunk right now. Do you have an idea about what is happening?

`(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96302d4dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Best,
Rafael Santos

**Comment by guilhemmarchand** [comment]
Hi @rafamss !

Hum this looks like a networking issue on your side, seems like the Jira target cannot be resolved.

DNS issue? Make sure you can curl the JIRA url from your search heads - looks like it's not the case 

Guilhem

**Comment by rafamss** [comment]
Thanks, Guilhem, We'll try this here and get back to you.

**Comment by rafamss** [comment]
Hi @guilhemmarchand,

We tried a curl to our Jira URL, and the result was:

```
splunk@sh818239723601282:~$ curl -k https://our_jira.atlassian.net
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>AtlassianProxy/1.19.3.1</center>
</body>
</html>
```

Anything else to test?

Best,
Rafael Santos

**Comment by guilhemmarchand** [comment]
Have you checked:
https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/configuration.html#configuring-an-account-with-api-
token-for-atlassian-cloud

Especially, for Altlassian Cloud customers, look at:
https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

You issue is out of the TA or Splunk question really, Atlassian provides you with an API you can reach easily, mine for ex is:
curl -v -k https://guilhem.atlassian.net

If you can’t do that, maybe that’s the fault of your network constraints, guessing your traffic is intercepted locally for example, and you have to an HTTP proxy from your company, which the TA fully supports

**Comment by guilhemmarchand** [comment]
Update: Splunk Cloud is re-installing the app from scratch as we could not idenfity the root cause, however the app works as expected in the exact same Splunk Cloud version so it is linked to the customer's environment

**Comment by guilhemmarchand** [comment]
This was fixed AFAIK
