### ISSUE TITLE
Fix - Configuration of the account fails if trailing slash is left in the URL

### ISSUE THREAD

**Issue by tscheid** [guilhemmarchand/TA-jira-service-desk-simple-addon#127]
Hi Guilhem,
We have a local Jira installation, when I explore the REST API I get  
JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 353 : Expecting ',' delimiter: line 1 column 69 (char 68)
and in the search.log something like 
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr: JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 353 : Expecting ',' delimiter: line 1 column 69 (char 68)
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr: Traceback:
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/lib/splunklib/searchcommands/search_command.py", line 780, in _process_protocol_v2
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     self._execute(ifile, None)
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/lib/splunklib/searchcommands/generating_command.py", line 207, in _execute
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     self._execute_v2(ifile, self.generate())
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/lib/splunklib/searchcommands/search_command.py", line 961, in _execute_v2
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     self._execute_chunk_v2(process, result)
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/lib/splunklib/searchcommands/generating_command.py", line 215, in _execute_chunk_v2
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     for row in process:
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/bin/jirarest.py", line 271, in generate
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     data = {'_time': time.time(), '_raw': str(json.dumps(json.loads(json_response, strict=False), indent=4))}
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/json/__init__.py", line 361, in loads
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     return cls(**kw).decode(s)
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/json/decoder.py", line 337, in decode
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/json/decoder.py", line 353, in raw_decode
12-09-2021 11:42:51.480 ERROR ChunkedExternProcessor - stderr:     obj, end = self.scan_once(s, idx)
I configured basic authentication using username and password, no ssl verification. I also tried API token, didn't work either

**Comment by guilhemmarchand** [comment]
Hi @tscheid 

This only means that you are likely failing to authenticate properly.

If you are a Cloud customer of Jira:

- https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/configuration.html#configuring-an-account-with-api-token-for-atlassian-cloud

You need to use your username with basic authentication, then in the password box you use the API token you created.

If you are using Jira on-prem:

-  https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/configuration.html#configuring-an-account-with-personal-access-token-for-jira-on-premise-pat

You want to use a PAT based authentication, or basic with username / password

In any case, you want to test the authentication ideally if you can (unless you are a Splunk Cloud customer):

https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/troubleshoot.html

**Comment by tscheid** [comment]
Hi Guilhem,


A test with curl -k https://<ip:port>/rest/api/latest/project<https://%3cip:port%3e/rest/api/latest/project> --user splunktest:splunktest

Is successful, this is on-prem

**Comment by guilhemmarchand** [comment]
@tscheid 

Can you screenshot your app configuration window 

In the URL you need to put the server and port but not the rest of the URL which is added automatically.

For the credentials, on premise you would prefer to use PAT but you can use password too

**Comment by tscheid** [comment]
Is it possible that this is caused by the fact that I have to use IP instead of a hostname?
![image](https://user-images.githubusercontent.com/39992229/145403913-f24b0cca-49b1-455f-9abc-682380aca748.png)

**Comment by tscheid** [comment]
![image](https://user-images.githubusercontent.com/39992229/145403988-cfba12d3-28f7-4fbc-a970-91eaf32c2ba3.png)

**Comment by guilhemmarchand** [comment]
I will double check but please:

- remove the https:// 
As mentioned in this screen it is not required

- remove the remaining / at the end 

Both IP/fqdn will work

**Comment by tscheid** [comment]
Removing https:// and the trailing / did indeed fix it. I obviously didn't understand the documentation
Thanks for your help

**Comment by guilhemmarchand** [comment]
Perfect @tscheid glad it's ok now

I will verify, the backend should remove the trailing slash and normally the https is supposed to be verified if present 
I suspect the trailing slash to be the root cause but I need to check
