### ISSUE TITLE
Jira project overview only show first 4 projects ??

### ISSUE THREAD

**Issue by davipoul** [guilhemmarchand/TA-jira-service-desk-simple-addon#132]
Hi,

it seem that even if in the "Get project" section or in the alert action, all projects are correctly retrieved..the "Overview - JIRA Projects" get only the first 4 projects in the list.

From the query used behind, i'm not sure if it not the "spath" command in splunk without the "path" parameter is restrictied to only 5000 caracteres in auto-extra mode....

I did some basic test in splunk and without beeing expert maybe the following can be a starting point for investigation on your side..

Adding this into the spath section of the query: path={}.key

Example : | jirarest account="Jira_Groupe_Canam_POC" target="rest/api/2/project" | spath path={}.key | rename "{}.key" as key | table key | rename key as projects | eval projects_csv=mvjoin(projects, ",") | stats dc(projects) as dcount

give me all the 26 Jira projects (archived and actives).

Let me know if this can be improved or part of improvement..or if we can use kind of workaround to have all projects.

Thank

**Comment by guilhemmarchand** [comment]
Hi @davipoul !

Thank you for opening this issue, I will be reviewing it as soon as possible.

I think a more approriate way for the TA would be deal with this at the Python level within a custom command, and render the JSON data accordingly.

Which would address performance issues with the current approach too.

I will revert on this.

**Comment by guilhemmarchand** [comment]
Hi @davipoul 
This finally is addressed in v 2.0.11 ;-)
https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/userguide.html#jira-overview-custom-command
