### ISSUE TITLE
Unable to create tickets manually in Jira using |sendalert command

### ISSUE THREAD

**Issue by archashaji1** [guilhemmarchand/TA-jira-service-desk-simple-addon#137]
Hi, We are trying to integrate Splunk Cloud with our Atlassian Jira cloud instance. We have configured the app 'Jira Service Desk Simple Add-On'(https://splunkbase.splunk.com/app/4958/) and under 'Trigger Actions' I am able to see this action and also able to create/open ticket in Jira via this option.
 But I want to create ticket in Jira manually via splunk query using 'sendalert' command. It is returning error "Error in 'sendalert' command: Alert script returned error code 1."
The adhoc search I am runnning:
|sendalert jira_service_desk param.account=“JiraCloud” param.projectKey=“SOR” param.issueTypeName=“Task” param.priority=“Low” param.summary=“TEST_GSuite.1_UserReportedPhishing - Alert from Splunk”

Please let me know what is it that I'm doing wrong.

**Comment by guilhemmarchand** [comment]
Hi @archashaji1 

The following is an example:

```
| makeresults
| eval description="test alert dyn priority", content="foo and bar all together", jira_priority="High"

| sendalert jira_service_desk param.account="LAB" param.jira_project="LAB" param.jira_issue_type="Bug" param.jira_priority="$result.jira_priority$" param.jira_description="Test JIRA alert" param.jira_summary=$result.content$
```

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/7503059/176039705-67298ac3-6358-4d2c-96b6-6fe3627fdca6.png">

The arguments you are submitting are not those expected, you can see the arguments in alert_actions.conf:

https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/blob/master/package/default/alert_actions.conf

**Comment by archashaji1** [comment]
Thank you ! That was really helpful!
