### ISSUE TITLE
add a field for component 

### ISSUE THREAD

**Issue by hamidbg86** [guilhemmarchand/TA-jira-service-desk-simple-addon#15]

**Comment by hamidbg86** [comment]
this is for adding a new field in the addon when creating an action in splunk to have the component type: incidents, and so forth

**Comment by guilhemmarchand** [comment]
@hamidbg86 

The version 1.0.11 is live in Splunk Base and addresses this enhancement request.

Guilhem

**Comment by hamidbg86** [comment]
Thanks Guilem, you're the best!

**Comment by guilhemmarchand** [comment]
Ha ha ;-) With pleasure let me know if any issues.

**Comment by hamidbg86** [comment]
will sure do. I will test it tomorrow and let you know.
thanks!
