### ISSUE TITLE
Edit "pending" issues

### ISSUE THREAD

**Issue by poiromaniax** [guilhemmarchand/TA-jira-service-desk-simple-addon#169]
Hi

Firstly - thanks for this super useful addon. Its made my life a lot easier!

I have a situation where the custom field was misconfigured in the alert action, and it attempted to create tickets into an epic that didnt exist.

I have fixed the alert action, but I can see that I have a bunch of "pending creation" issues that will continuously fail because they are still attempting to use the wrong customfield

Is there any way to edit these pending events to fix the customfield?
I would really like to have these tickets created without having to mess around with the alert criteria.

Thanks!

**Comment by guilhemmarchand** [comment]
Hi @poiromaniax 
You are welcome ;-)

Just clear out the replay KVstore, run the following search:

```
| outputlookup jira_failures_replay
```

**Comment by poiromaniax** [comment]
@guilhemmarchand that will delete them completely right?

There is a backlog there going back a couple of days, which means I would lose those pending tickets as the alert wont create them again

**Comment by guilhemmarchand** [comment]
Sorry I've read quickly

You can just edit the KV records with the lookup editor in do it in SPL:

```
| inputlokup jira_failures_replay | eval key=_key
| rex field=myfield mode=sed "s/mybadvalue/mygoodvalue/g"
| outputlookup jira_failures_replay append=t key_field=key
```

This is an example using rex, could be with eval etc

**Comment by poiromaniax** [comment]
Thanks - I tried with that example, by modifying it like so:
`| inputlookup jira_failures_replay | eval key=_key
| rex field=fields.project.customfield_10008 mode=sed "s/IS-7531/IS-7530/g"
| outputlookup jira_failures_replay append=t key_field=key`

I havent found the correct "syntax" to use to modify the field.
You can see the field Im trying to change at the bottom, but doesnt seem to be doing anything
![image](https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/assets/15910083/e97a023e-f35b-4cc8-ad51-13ba9872c507)

**Comment by guilhemmarchand** [comment]
@poiromaniax 

The field should not be called with dots in it

This is the list of fields you should see from the inputlookup:

account, data, status, ctime, mtime, no_attempts

Basically this is data that contains the REST call representation - if you see fields with dots then something unexpected happened with the custom field structure and better flushing the KVstore (the original outputlookup)

**Comment by poiromaniax** [comment]
@guilhemmarchand aaaahhhhh got it.

Thanks for that - successfully changed it now (`data` field) and it should create them on next retry!
Much appreciated
