### ISSUE TITLE
custom fields are not populated when creating issue

### ISSUE THREAD

**Issue by migul1** [guilhemmarchand/TA-jira-service-desk-simple-addon#172]
Hello.

During issue creation with Jira Service Desk  , custom fields get ignored i.e. an issue gets created with mandatory fields, like  description, summary, etc., however custom fields are not populated

Syntax of CF like 

"customfield_21264": "Hello" 

______________________________________________

I can successfully set this CF  if I create issue via HTTP with Curl

$ curl -k -u 'account:password' --request POST --url 'https://jira-host/rest/api/2/issue' --header 'Accept: application/json' --header 'Content-Type: application/json' --data '{"fields": { "project": { "key": "PROJ" }, "summary": "Pictures", "description": "SIEM-Eng", "issuetype": {"name":"Event"}, "customfield_21264": "Hello"}}'

UPD:

According to LOG

`2023-08-14 13:24:37,690 ERROR pid=116436 tid=MainThread file=cim_actions.py:message:292 | sendmodaction - signature="Failed to load jira_customfields="{customfield_21264": "Hello}" as a proper formated JSON object with exception="Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"" action_name="jira_service_desk" sid="1692012268.44302" orig_sid="scheduler__nobody_REJHX1VTRV9DQVNFX1RFU1RfQVBQ__RMD50e36bf240caf243c_at_1692001800_50431" rid="0" orig_rid="0" app="SplunkEnterpriseSecuritySuite" user="xxx" 
action_mode="adhoc" action_status="failure" `

The first and the last quotas (") get cut by parser

="Failed to load jira_customfields="{customfield_21264": "Hello}"

Solution pending :confused_face:
`

**Comment by guilhemmarchand** [comment]
Sorry for the delay @migul1 !

Actually. an issue was identified which is likely causing this for you too - will be fixed in release 2.0.17
