### ISSUE TITLE
Add more detail for the alert 

### ISSUE THREAD

**Issue by hamidbg86** [guilhemmarchand/TA-jira-service-desk-simple-addon#18]
In a splunk email alert we are able to add different elements like below : 
![image](https://user-images.githubusercontent.com/31827356/85299155-e9ccb580-b472-11ea-9bcf-841ab6e73f49.png)

Would that be something that can be added to the add-on? 

Thanks Guilhem!

**Comment by guilhemmarchand** [comment]
@hamidbg86 

This might be possible, I will check it out.

**Comment by hamidbg86** [comment]
@guilhemmarchand  Thank you!

**Comment by hamidbg86** [comment]
@guilhemmarchand  Hello Guilhem, 

Just checking to see if you have updates on this one. 

Thanks!

**Comment by guilhemmarchand** [comment]
Not yet @hamidbg86 no.

If you have additional comments on this, please feel free to do so

**Comment by hamidbg86** [comment]
Hello Guilhem, 
I was able to change the subject of the email by adding the following to spl : 
... | eventstats values(host) AS _host_list values(filename) AS _file_list values(everity) AS _severity_list
| nomv _host_list | nomv _file_list | nomv _severity_list

In the subject of the alert I just had to put for example $_host_list$ and it picks the hostname from the search result. 

The issue now is being able to add a csv, document and result of the alert to the event being logged into JIRA. 

Thanks Guilhem.

**Comment by guilhemmarchand** [comment]
@hamidbg86 

It turns out that attaching the alert results is a more challenging that it could seem. (not on the JIRA side, more a Splunk thing)

Therefore, during my testing, I successfully can attach to the created JIRA issue the Splunk alert dispatch file results as the results.csv.gz. ($results_file$ from a Splunk token point of view)

Would you think this addresses your need, or the file attached to the ticket has to be in a uncompressed format ?

**Comment by hamidbg86** [comment]
Hello Guilhem,

right, by using these token they help me resolve the problem.
thanks!

**Comment by guilhemmarchand** [comment]
@hamidbg86 

Sure, by the way I found out this doc page that summaries the token specially the Meta token which are as well available for the JIRA action:

https://docs.splunk.com/Documentation/Splunk/8.0.4/Alert/EmailNotificationTokens

I am finalising a new version which will contain an option to add automatically as an attachment to the JIRA issue the results from the alert. (working already, doing some improvements)
The result link was added to the description field by default.
Other options IMO are not specially valuable.

Guilhem

**Comment by guilhemmarchand** [comment]
@hamidbg86 

Version 1.0.12 is live in Splunk Base:

- Feature: Issue #18 - New option on a per alert basis allows automatically attaching Splunk alert results to the JIRA issue in CSV or JSON format
- Feature: Issue #18 - Add by default in the description field the result link token call

The attachment feature is documented here:

https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/userguide.html#jira-attachment

Let me know if you have questions ;-)

**Comment by guilhemmarchand** [comment]
I assume we can close this issue @hamidbg86 , let me know otherwise.

Guilhem

**Comment by hamidbg86** [comment]
Thanks Guilhem, yes please!
