### ISSUE TITLE
I cannot find this release on the splunk cloud.

### ISSUE THREAD

**Issue by CowboySoftware** [guilhemmarchand/TA-jira-service-desk-simple-addon#190]
I cannot find this release on the splunk cloud.
Is this release support to Splunk Cloud?

**Comment by guilhemmarchand** [comment]
Hi @CowboySoftware 

For any Splunk App, when a new release is published in Splunk Base, the release has to go through Splunk Cloud vetting before it can be available for Splunk Cloud customers. (and if it passes the initial Appinspect check from Splunk Base, which is the case for this new release)

This is a process handled by Splunk, which can take little from just a few days to several weeks depending on them.

**Comment by CowboySoftware** [comment]
Thank you for information
