### ISSUE TITLE
FIPS error when creating tickets

### ISSUE THREAD

**Issue by jake-choi-cf** [guilhemmarchand/TA-jira-service-desk-simple-addon#197]
Hello,

I'm receiving an error when Splunk attempts to create Jira tickets. I've confirmed that the Jira projects are visible in the dashboard which means that the account configuration is correct and Jira is reachable. However, I'm noticing that the logs are saying that hte ticket is failing to be created. The error appears to only affect Splunk versions 9.3+ as I'm not noticing the issues in environments using Splunk 9.2. 

An example of the error message:  ERROR tid=MainThread file=cim_actions.py:message:292 | sendmodaction - signature="Unexpected error: [digital envelope routines: FIPS_DIGESTINIT] disabled for fips." action_name="jira_service_desk"

**Comment by guilhemmarchand** [comment]
Hi @jake-choi-cf 

I see where the issue stands, the app uses md5 for different purposes which was (sliently) fixed since Splunk 9.3.0.
In FIPS, md5 is considered weak and should be disabled, Splunk wasn't honouring that, I need to migrate the app to use sha256 instead. (did for some other apps)

Will look at it for a release update

**Comment by jake-choi-cf** [comment]
Thank you for looking into it and the quick response! 

Would you happen to have a target date for the next release?

**Comment by guilhemmarchand** [comment]
Starting the work @jake-choi-cf  - planning to release by end of the week - sorry for being late.

**Comment by guilhemmarchand** [comment]
@jake-choi-cf 

Release 2.0.19 is now in Splunk Base and compatible with FIPS - please be kind enough to confirm things work as expected on your end.

**Comment by jake-choi-cf** [comment]
@guilhemmarchand 

Just pushed out the updated version and Jira is working now! Thank you for the update!

**Comment by guilhemmarchand** [comment]
Very happy to read that @jake-choi-cf ! Thanks for confirming ;-)
