### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by markusspitzli** [guilhemmarchand/TA-jira-service-desk-simple-addon#2]
I installed your "Add-on for Atlassian JIRA Service Desk alert action" from Splunkbase and configured it. 
I receive KeyErroros when I start a command like this: 
"| jirafill opt=1 | stats count by key, key_projects | dedup key_projects | sort key_projects | fields key, key_projects"

Errors:
    [idx001] KeyError at "/opt/splunk/var/run/searchpeers/shiscs01.461-1587717300/apps/TA-jira-service-desk-simple-addon/bin/ta_jira_service_desk_simple_addon/aob_py2/splunklib/client.py", line 1703 : 'ta_jira_service_desk_simple_addon_settings'

Our configurations looks like:
[additional_parameters]
jira_password = ********
jira_ssl_certificate_validation = 1
jira_url = https://jira.mycompany.com
jira_username = serviceaccountname

Another Error I found in the search.log:
04-24-2020 11:02:40.410 ERROR ChunkedExternProcessor - stderr: /opt/splunk/etc/apps/TA-jira-service-desk-simple-addon/bin/ta_jira_service_desk_simple_addon/aob_py2/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Thats strange. because Validation is on.

**Comment by guilhemmarchand** [comment]
Acknowledged, the custom commands should honour the SSL verification option too.

Will be fixed in next release.

**Comment by guilhemmarchand** [comment]
Fixed in Version 1.0.3.
