### ISSUE TITLE
Suggestion: don't deduplicate closed issues

### ISSUE THREAD

**Issue by jacobappleton-orbis** [guilhemmarchand/TA-jira-service-desk-simple-addon#33]
Firstly, thanks for writing this add-on, it looks really helpful!

I'd like to suggest an improvement. It would be really helpful for us to have this add-on only de-duplicate the issue for certain statuses. i.e. de-duplicate an open issue, but don't de-duplicate a closed one. I suspect you'd want to have the user who is setting up the alert choose which statuses to de-duplicate.

The actual logic to manage this seems like it would be fairly straight-forward and fit in here: https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/blob/36c4d3f3a1c19a749e84508f2fbb90e685672bfd/TA-jira-service-desk-simple-addon/bin/ta_jira_service_desk_simple_addon/modalert_jira_service_desk_helper.py#L398 The code could inspect the field `status.statusCategory.name` from the result from calling `jira_url + "/" + str(jira_backlog_key)`. 

I haven't looked further on adding a list of statuses to the alert page, but I imagine this would be done in a similar way that other data is added to the alert page.

If I find some time in the next few weeks, this is something I'd like to contribute to. Otherwise it would be a great improvement if you have time!

**Comment by guilhemmarchand** [comment]
Hi @jacobappleton-orbis !

Thanks for looking into this, I will be more than happy to welcome your participation ;-)

it's an interesting idea yes, this would suppose some additional bi-directional communication which wouldn't very difficult to achieve I agree, the logic is there already and it would just be an additional rest call to retrieve the current ticket status and act accordingly.

Let me know if you have any question, I will have a look too when I have some time free!

Guilhem

**Comment by guilhemmarchand** [comment]
@jacobappleton-orbis 

I have merged an update into the testing branch for this (from version_1019), which in shorts does the following:

- A new option allows customizing the list of statuses to be excluded out of the box from the deduplication, which defaults to Closed,Completed,Canceled
- When the alert triggers, if dedup is enable a REST call is made to JIRA to get the current status of the issue, dependending on the status the relevant action is taken and logged, such as:

Example:

`jira_dedup: The issue with key TEST-90021 has the same MD5 hash: d50828c514c4df7231eab2be96363991 and its status was set to Closed in JIRA, a new comment will not be added to an issue in this status, therefore a new issue will be created.
`

`jira_dedup: The issue with key TEST-90025 was set to status Open in JIRA, therefore, a new comment will be added to this issue.
`

Let me know if you have any remarks ;-)

Guilhem

**Comment by jacobappleton-orbis** [comment]
Wow, you're fast! I only just saw this.

I submitted a PR that does something very similar. Let me know what you think. It grabs the status categories from the API, and uses those instead. It also handles updating the md5 hash when the issue is closed.

**Comment by guilhemmarchand** [comment]
Oh really @jacobappleton-orbis ! What a shame ;-)

This songs very interesting, I will have a look now, grabbing the status categories automatically is nice too, not sure yet if this would fit all customer use cases as some are keen to re-create their own entire categories.
Updating the hash looks very interessing, let me check if this can be merged now

Thanks!

**Comment by jacobappleton-orbis** [comment]
I'm not sure if there's a way to do multi-select in the UI for the alert action - then you could grab the statuses dynamically and select the ones you want. I couldn't find anything helpful there over the weekend, so I stuck with status category, which feels like it was made for our use case :)

**Comment by guilhemmarchand** [comment]
I see, yes that could make sense (the status categories), however indeed I don't think there are any easy way to get a multiselect natively in the alert UI

**Comment by guilhemmarchand** [comment]
@jacobappleton-orbis 

So currently I had to import part your work manually, in the testing and version_1019 branch:

https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/tree/testing

My apologise, our commit happened in a very short time with different approaches, plus another related feature (https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/issues/34)

So basically what I did:

- Imported the new report, the additional option in jirafill.py, and change in nav/default.xml
- Imported the jira completed logic which deletes the record in the backlog collection once the ticket reached a completed state, thank you very much for this one!

Regarding the status categories, I need to think a bit more about it, I am keen to think the stasuses approach is easier for users, especially an existing deployment would need to go over each existing alert to update it to be use the feaure, and there might not much way to know in advance which category is related to the completed stasuses, but maybe not ;-)

I need to improve opening this repo to collaboration, thanks for it I much appreciate!

Will catch up a bit later

**Comment by jacobappleton-orbis** [comment]
No problem, totally understand.

My preference is to use statusCategory, as it is quite onerous for users to select all the statuses they wish to ignore.

Perhaps we could provide both as an option?

**Comment by guilhemmarchand** [comment]
Hi @jacobappleton-orbis 

I did some JIRA reading and researches earlier, from my understanding JIRA does not allow the creation of new status categories, for instance:

https://community.atlassian.com/t5/Jira-questions/How-can-I-create-a-status-category/qaq-p/764219

Which means that all statuses to be ignore would be associated with the "Done" status category, so my thinking is the following:

- There is not need to provide an option per alert (nor list of statuses, nor list of status categories to be selected)
- The Python code would use your logic to retrieve the status category of the current status (so a mix of your code and mine) then if the current status is part of the Done status, we would consider the JIRA completed

Let me know your thinking ;-)

**Comment by jacobappleton-orbis** [comment]
This would work for my use case, but is it possible that someone might want to deduplicate "Done" issues?

**Comment by guilhemmarchand** [comment]
I guess it might not be impossible but certainly it would be some form of misunderstanding of the status meaning / workflow that should be applied from JIRA perspective, a status in the Done category should not be actively receiving programatic inputs, otherwise it's not in the right status. (just my 2 cents I'm no scrum master ;-)

I like the idea because we avoid the manual interaction on the config side, we keep the functionally at its best level and we keep the dynamic approach and the great stuff you came with

**Comment by jacobappleton-orbis** [comment]
I agree it would be quite unusual, but my instinct is to give the users the choice. Perhaps we could even default it to ignore "Done", and the user can change it if they really want to?

Agree that it sounds like the best way forward. Thanks for working on this so quickly!

**Comment by guilhemmarchand** [comment]
@jacobappleton-orbis 
Implemented in version 1.0.19 which is now live in Splunk Base
