### ISSUE TITLE
Suggestion: Allow Deduplication to ignore some information when calculating the MD5 hash

### ISSUE THREAD

**Issue by Zachary-Mikus** [guilhemmarchand/TA-jira-service-desk-simple-addon#34]
First off, love the new deduplication feature.

However, the issue we're having is that if the information posted to JIRA contains any dynamic values whatsoever, then it's not going to be considered a duplicate.

For instance, if I have an alert that has produced the exact same results but am providing a link to the Alerts search job for an analyst. Everytime the alert runs the Search Job ID will be different, ergo they will not be considered duplicates. 

Another example may be that an IP triggering an alert over failed/successful actions may have a different number of failed/successful actions each time the alert fires. So we currently have to either exclude this information from the alert, to the detriment of our analysts, or severely limit the effectiveness of the deduplication function. 

A solution to this may be that after Enabling Deduplication for an alert, that it provides you with an optional input box where you can place information that won't be calculated as part of the MD5, but when posted to JIRA will be concatenated to the contents of the "Description" input. This way we have far more control over what the AddOn will consider a duplicate and what it won't consider a duplicate.

**Comment by guilhemmarchand** [comment]
Hi @Zachary-Mikus 

Thank you submitting this new feature enhancement idea and request, much appreciated.

Indeed the current behaviour of the deduplication feature is to issue an MD5 calculation against the entire JSON data which represents the full rest call data made against JIRA, shall anything change in the data, this is not considered as a duplicate issue and this will results in the creation of a brand new JIRA issue.

I will be taking this in consideration and will work to provide additional options to restrict what should be taken in to account for the MD5 sum calculation to provide more control on this.

Guilhem

**Comment by guilhemmarchand** [comment]
Hi @Zachary-Mikus 

**I have been working on this enhancement request, and I am proposing the following feature:**

- A new option is added on a per alert basis, this allows defining the scope of the md5 calculaton content
- Basically, if this field is filled, this automatically switch the dedup mode full to false and uses this content to perform the md5 calculation

![image](https://user-images.githubusercontent.com/7503059/93121852-6f9c7d80-f6bd-11ea-93f8-2a7948a9d1ce.png)

- This allows any kind of granular control, in I think the better and more performing way.

If you have a testing environment and whish to have a look ;-)

https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/tree/testing

Cheers

Guilhem

**Comment by guilhemmarchand** [comment]
@Zachary-Mikus 
Implemented in version 1.0.19 which is now live in Splunk Base
