### ISSUE TITLE
Suggestion: Removing Priority as a Required Input

### ISSUE THREAD

**Issue by dantimola** [guilhemmarchand/TA-jira-service-desk-simple-addon#42]
As discuss some Jira environment are not requiring to input a ticket priority, our use case is one of the examples. Instead of using priority, we are using "Security Incident Severity".

Ticket prioritization is automatically selected by our Jira.

Thanks.

**Comment by guilhemmarchand** [comment]
Test and approved, will be in 1.0.19.

**Comment by guilhemmarchand** [comment]
@dantimola 
Implemented in version 1.0.19 which is now live in Splunk Base
