### ISSUE TITLE
Suggestion: Only query projects user can raise issues in

### ISSUE THREAD

**Issue by jacobappleton-orbis** [guilhemmarchand/TA-jira-service-desk-simple-addon#51]
Currently the JIRA project query returns all projects that the user can see, but if possible we should filter this to projects the user can raise an issue on. Otherwise it will appear as though the alert has not fired, even though it has (unless you check the add-on logs).

**Comment by guilhemmarchand** [comment]
Will not be done, while this certainly could be making sense for some use cases, this is at the small margin and would require that the JIRA integration be made on per user profile rather on a per service account basis which would be the standard for a third party integration.
