### ISSUE TITLE
Have Reporter as a Field Option for Alert Trigger Action

### ISSUE THREAD

**Issue by jenniferfusco** [guilhemmarchand/TA-jira-service-desk-simple-addon#65]
We make the affected party the reporter of the issue and would love to have that as an easier option when creating the ticket.

**Comment by guilhemmarchand** [comment]
Hi @jenniferfusco,

Right, I will look into this anytime soon, an option allowing to set the reporter based on a static or dynamic (from Splunk results) should be easy doable.

Guilhem

**Comment by jenniferfusco** [comment]
Thanks so much @guilhemmarchand !!!!

**Comment by guilhemmarchand** [comment]
@jenniferfusco 
Will be in 1.0.24 to be published shortly.

**Comment by guilhemmarchand** [comment]
done done.
