### ISSUE TITLE
Update vs Dedup features

### ISSUE THREAD

**Issue by johnyoon-tempus** [guilhemmarchand/TA-jira-service-desk-simple-addon#78]
I was wondering if there was a functionality to automatically update an existing ticket, instead of generating a new one?

For example, if I had a ticket with the description "Hello," and wanted to update the ticket to say "Hello World"?

Similarly, is there a way to update the attached csv file?

**Comment by guilhemmarchand** [comment]
Hi @johnyoon-tempus 

The purpose of the dedup feature is to add a comment to an existing Jira issue, rather than creating a new issue when the content is the same and the conditions are met.

The feature is documented here:

https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/userguide.html#jira-dedup-behavior

So, in short, a new ticket wouldn't be created but it will add a comment which you can customize.

Updating the description is certainly possible but not really in the idea of a dedup thing.

I would say same for the CSV

**Comment by johnyoon-tempus** [comment]
Thanks for the response!

In that case, how would someone automatically update the CSV on an existing ticket?

**Comment by guilhemmarchand** [comment]
pleasure @johnyoon-tempus 

So, may I ask why would you want to "update" the CSV in a JIRA, rather adding a new element?
I may be wrong, but I would more see each element added to the ticket life cycle as something that should not be altered and can help understanding the context and taking decisions.

Altering something that was attached to the ticket would IMO defeat this instead.

Adding new content would be totally doable via REST (which is what does the Python backend), a custom command in Splunk for instance could perform a POST call. (an extension of the existing jirarest command for example)

**Comment by johnyoon-tempus** [comment]
@guilhemmarchand I agree that this is less than an ideal approach.

The main reason why I want to "update" the CSV in a JIRA, rather adding a new element is because the data payload is too large for the JIRA ticket comment area. So CSV seems to be the only way to contain the information in a ticket.

**Comment by guilhemmarchand** [comment]
@johnyoon-tempus 

It would be possible to add (and not "update) a new CSV attachment to an existing ticket, either by:

- Using a custom command that recyles the result from a search, pipes to the command which requires in argument the ticket reference then add the results as a CSV attachment

- Achieves the same thing via an alert action logic, which would be called as an ad-hocs adaptive response in Splunk Enterprise Security, or a Splunk core alert

Let me know if that makes sense.

**Comment by guilhemmarchand** [comment]
Closed for inactivity.
