### ISSUE TITLE
Python Upgrade Readiness App complains about 'outdated Python SDK'

### ISSUE THREAD

**Issue by ViGblS** [guilhemmarchand/TA-jira-service-desk-simple-addon#83]
Hi Guilhem, in the run-up to upgrading to Splunk 8, we scanned the installed apps for compatibility.
The SplunkBase app 'Python Upgrade Readiness App (https://splunkbase.splunk.com/app/5483/)' in version 1.0 was used for this.
We're right now running Splunk 7.3.3.
Unfortunately, your app (V1.0.27) is shown as incompatible. Error message: This app contains an outdated Python SDK. Update to the latest Python SDK.

Looks like a false alarm in my opinion, I just want to make sure we don't get any problems with Splunk 8.

Thanks

**Comment by guilhemmarchand** [comment]
Hi @ViGblS 

I will check it and will reciew, I have started that work on others of my apps (TrackMe) and unfortunately that Python thing is generating a serious amount of false positives.

Talking about the TA, it is actualluy is possible compatible with Splunk 8.x and especially with Python 3, it actually is using Python 3.

Will review.

**Comment by guilhemmarchand** [comment]
@ViGblS 

Version 1.0.28 was published to fix this issue, these packages were not the Python SDK libs used by the app, but older versions originally stored in some internal packaging directories from Addon Builder.

Others failres reported by the Python readiness are false positive unfortunatevely raised by the incompatibe file path check in the Readiness app which is badly designed and cause the false positive detection even on pure py3 packages.
