### ISSUE TITLE
 sendmodaction - signature="json loads failed to accept some of the characters, raw json data before json.loads:

### ISSUE THREAD

**Issue by hamidbg86** [guilhemmarchand/TA-jira-service-desk-simple-addon#9]
While creating the alert in splunk I use the custom fields area to add the components because without it the API fails. 
the issue is when I put this "components": { "name": "Incidents" } it says the format is wrong. 

Can you please advise.

**Comment by hamidbg86** [comment]
I used postman to create an issue using "components": [{ "name": "Incidents" }] in the payload and it worked. 
but when I do that on the Alert setup in splunk, it does ass backward slashes and it says :
error: Expecting property name enclosed in double quotes: line 16 column 2 (char 291).

Can you please advise ? 

Thanks!

**Comment by guilhemmarchand** [comment]
Hi @hamidbg86 

Sorry for some reasons I didn't get notice of the issue.
Will review shortly.

Kind regards,

Guilhem

**Comment by guilhemmarchand** [comment]
@hamidbg86 

Can you confirm that you have tested with the version 1.0.8 of the addon ?

Version 1.0.8 introduced a fix to allow using the custom fields for non proper custom fields but other non standard fields

**Comment by guilhemmarchand** [comment]
Issue has been identified and is happening in a section of the Python code which role is to prevent the content of the custom fields (the real content not their format) to alter the JSON validity.

Will be fixed shortly

**Comment by hamidbg86** [comment]
thank you for the clarification.

**Comment by guilhemmarchand** [comment]
@hamidbg86 

Please upgrade to the version 1.0.10 which fixes this issue.
Let me know if you have any further questions.

Guilhem

**Comment by hamidbg86** [comment]
I would like to add another thing.
when sending alerts to Jira and using the issue type: Task it needs the
component added to it.
can you make component as a field to add like any other fields?

**Comment by guilhemmarchand** [comment]
I see it might be possible, would you mind opening a new enhancement request issue please ?
