### ISSUE TITLE
JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 353 - 1.0.30 - SH Cluster version 8.1.1

### ISSUE THREAD

**Issue by siberiac** [guilhemmarchand/TA-jira-service-desk-simple-addon#97]
Hey Team!

I've recently installed a fresh copy of the add-on to my search head cluster. I've entered my configuration options, and have verified that the user has access to the projects/issues that we're wanting to pull outside of the add-on.

Once configured, however, the REST API explore page doesn't populate with data as I have experienced in the past. I'm getting an error that appears as follows 

JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 353 : Expecting ',' delimiter: line 21 column 15 (char 161)

Any help troubleshooting this would be greatly appreciated!

**Comment by guilhemmarchand** [comment]
@siberiac This likely indicates that the connection to Jira is failing somehow.

Can you please go through a manual connectivity test using cUrl from one of the search heads:

https://ta-jira-service-desk-simple-addon.readthedocs.io/en/latest/troubleshoot.html

**Comment by siberiac** [comment]
So the authentication did fail, not because of a user/password issue, but when I went to the GUI to log in with the account I was prompted for a captcha to log in. Looks like that extra layer of authentication (wherever it came from) is what caused the block.

The app is working now, and I'll engage with the JIRA administrators to find out why that happened and how to prevent it again. 

Thanks for the help!

**Comment by guilhemmarchand** [comment]
@siberiac Glad you could identify quickly ;-)

Yes, currently the app only supports basic authentication, I am working on extending it to support oauth2 but not yet ready.
I shall try too to provide an easier way to test the authentication in Splunk directly!
