### ISSUE TITLE
Attach new result file while using dedup behavior

### ISSUE THREAD

**Issue by fanou51500** [guilhemmarchand/TA-jira-service-desk-simple-addon#98]
Hi Guillem,
Your add-on is awesome!
This is an enhancement request.
Having dedup behavior enabled, would it be possible to attach the new result file along with the new comment ?

**Comment by guilhemmarchand** [comment]
Thank you @fanou51500 much appreciated ;-)
And yes, sure, I can add this option.
Currently working on the v2 of the app I will include this

**Comment by guilhemmarchand** [comment]
@fanou51500 
Will be in version 2.0.0
