### ISSUE TITLE
Result file in xlsx format

### ISSUE THREAD

**Issue by fanou51500** [guilhemmarchand/TA-jira-service-desk-simple-addon#99]
This is an enhancement request.
Could you support xlsx format for result file ?

**Comment by guilhemmarchand** [comment]
@fanou51500 noted! This must doable yes, there's certainly a Python library for that 
Will check

**Comment by fanou51500** [comment]
Few librairies: http://www.python-excel.org/

**Comment by guilhemmarchand** [comment]
@fanou51500 
Will be available in version 2.0.0
